config/routes.rb
Rails.application.routes.draw do

  resources :audit_logs, except: [:new, :edit, :destory] do
    member do
      get :confirm
    end
  end

  get 'notifications/create'

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end
  get '/instructions' => "static#instructions"
  devise_for :users, skip: [:registeration]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#homepage'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "App Alert", sticky: false , time: 5000) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "App Error", sticky: false , time: 5000) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "App Notification", sticky: false , time: 1000) %>
<% end %>

app/views/shared/_nav.html.erb
<% if current_user %>
  <ul class="custom-nav nav nav-tabs">
    <li class="<%= active?(root_path) %>">
      <%= link_to "", root_path, class: 'glyphicon glyphicon-home' %>
    </li>
    <li class="<%= active?(posts_path) %>">
      <%= link_to "TimeEntries", posts_path , class: "glyphicon glyphicon-time" %>
    </li>
    <% if policy(AuditLog).index? %>
      <li class="<%= active?(audit_logs_path) %>">
        <%= link_to "Audit Log", audit_logs_path %>
      </li>
    <% end %>
    <li class="<%= active?(new_post_path) %>">
      <%= link_to "AddNewEntry", new_post_path, class: "glyphicon glyphicon-plus-sign" %>
    </li>
    <li class="dropdown pull-right">
       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
      <ul class="dropdown-menu">

          <li>
            <%= link_to "Admin Dashboard", admin_root_path %>
          </li>
         
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>